SYNTAXNET_DIRECTORY="/home/abhishek/models/syntaxnet"
INPUT_TEXT_DIR="/home/abhishek/PycharmProjects/TriplesExtractor/inputfiles"
TEMP_WORKING_DIR="/home/abhishek/PycharmProjects/TriplesExtractor/workingdir"
DONE_DIR="/Users/abhsingh/PycharmProjects/TripleExtractor/donedir"
OUTPUT_TRIPLES_DIR="/home/abhishek/PycharmProjects/TriplesExtractor/output"