SYNTAXNET_DIRECTORY="/Users/abhsingh/models/syntaxnet"
INPUT_TEXT_DIR="/Users/abhsingh/PycharmProjects/TripleExtractor/inputfiles"
TEMP_WORKING_DIR="/Users/abhsingh/PycharmProjects/TripleExtractor/workingdir"
DONE_DIR="/Users/abhsingh/PycharmProjects/TripleExtractor/donedir"
OUTPUT_TRIPLES_DIR="/Users/abhsingh/PycharmProjects/TripleExtractor/output"